### ISSUE TITLE
Without a hue bridge, the server fails to load

### ISSUE THREAD

**Issue by danehammer** [zachfeldman/alexa-home#1]
I would like to work on this with you, so I'm telling you about this, seeking direction. Looks like the modules need to be pluggable, so a user can specify a set of them. I got it working with just nest, by merely commenting out the require lights line in app.rb. How would you envision this being implemented, some config in config.ru?

**Comment by zachfeldman** [comment]
Hey there @danehammer , thanks for contributing in advance! So the way I'd like to tackle this is create a config.yml file in the main directory that loads a set of options. For instance:

``` ruby
modules:
  -hue
  -nest
  -iriver
```

and then each of these modules is included with an if statement before the require to see which modules have been requested.

Think you could implement and send a pull request?
