### ISSUE TITLE
Looks like Alexa is getting Native Hue Integration

### ISSUE THREAD

**Issue by sarkonovich** [zachfeldman/alexa-home#15]
Tonight when I issued a lights command, Alexa came back with a strange answer:  "Could not find any connected home devices."

When I said, "Find connected home devices" she replied:

"Starting discovery. If you have a Philips Hue Bridge, press the button."

It seems she found all the lights, including Wemo lights, just judging by the number of connected home devices she reported finding. 

She can't control anything yet...light commands don't work [yes she can...see below]  But it seems like it's coming very soon.  We'll see if it's as good as your amazing project -- and if it isn't, I hope it doesn't interfere with it!

**Comment by KellyMahan** [comment]
I noticed the same thing working on my Wink integration. I hope they don't limit it to what is considered Connected Home™ devices.

**Comment by sarkonovich** [comment]
Sure enough..

The Echo app now has an entry for "Connected Home Devices."

It lists all my Hue and Wemo lights. You can create groups in the app. So far, all you can do is turn them off and on and dim them. No colors for Hue, or scenes (which I've gotten working.)  

Amazon is moving fast!

**Comment by zachfeldman** [comment]
Woah guys!!! This is soooo coool.

Honestly, they probably were inspired by this project and other similar ones.

If they're smart, they'll build in features people actually want, right? And if we were able to build an integration this easily, imagine how it was for them...

**Comment by hancho123** [comment]
Got an email from Amazon

Amazon Echo
WeMo and Philips Hue products now work with Amazon Echo.

You can now use Echo to switch on the lamp before getting out of bed, turn on the fan or heater while reading in your favorite chair, or dim the lights from the couch to watch a movie—all without lifting a finger...or even raising your voice.

To get started, connect your WeMo and Hue devices to your home Wi-Fi and name them in their respective app. Then say, "Alexa, discover my appliances." After Echo's confirmation, you can control your devices by voice.

Things to try:

"Alexa, turn on the hallway light"
"Alexa, turn on the coffee maker"
"Alexa, dim the living room lights to 20%"
"Alexa, turn on the electric blanket"
"Alexa, turn on the outdoor decorations"
Supported products:

WeMo: Switch, Insight Switch, and Light Switch
Hue: A19, Lux, BR30, Bloom, and LightStrip lights
As always, the Amazon Echo team looks forward to your feedback via the Amazon Echo App and on social media (#AmazonEcho).

**Comment by sarkonovich** [comment]
Yes!

I've found that the Echo's Hue support is just a little buggy. I have 15 hue lights, and if tell the Echo to turn them all of or on, it only gets about 80%. 

Once the bugs get squashed, we should remove the on/off and brightness functionality from this repo's Hue module and leave that to Echo (to avoid sending duplicated commands.) But still need the repo for colors (and calling up Hue Scenes -- a feature I'm working on now.)

I assume, though, that before too long all the Hue features will be native on the Echo!

**Comment by zachfeldman** [comment]
I think you're right @sarkonovich . Our time here is limited...
