### ISSUE TITLE
Getting weird output from Raspberry Pi and Chrome

### ISSUE THREAD

**Issue by hancho123** [zachfeldman/alexa-home#3]
Hi Zach! Just putting what I posted on your blog on Github.

Some questions...

I got everything to run, but I get some weird things on Raspberry Pi when I run the startupScript.sh:

$ /home/pi/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:20:in `bridge': Hue::NoBridgeFound (Hue::NoBridgeFound)
    from /home/pi/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:49:in`validate_user'
    from /home/pi/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:14:in `initialize'
    from /home/pi/dev/alexa-home/modules/lights.rb:4:in`new'
    from /home/pi/dev/alexa-home/modules/lights.rb:4:in `<top (required)>'
    from app.rb:8:in`require'
    from app.rb:8:in `<main>'
"Error: Address family not supported by protocol - socket(2) for \"::1\" port 7055"
watir-login.rb:80:in`rescue in start_crawler': undefined method `last_command' for nil:NilClass (NoMethodError)
    from watir-login.rb:74:in`start_crawler'
    from watir-login.rb:86:in `<main>'

Then I think the app.rb and watir-login.rb quits, because I run ps aux | grep ruby and those 2 are no longer showing.

Lastly, I do the jquery insert in Chrome and I keep getting this:

GET http://localhost:4567/command?q=&_=1425397524539 net::ERR_CONNECTION_REFUSED
GET http://localhost:4567/command?q=alexa%20stop&_=1425397524541 net::ERR_CONNECTION_REFUSED

I don't have Hue so obviously that's not working, but I'm thinking something is up with the ports in sinatra. Is it my router? Not sure...

Lastly, I found a typo in your read me file: "chmod +x startScript.sh && ./startupScript.sh". Should be "chmod +x startupScript.sh && ./startupScript.sh"

Thank you so much for the awesome write up! I'm enjoying your blog!

![original-1](https://cloud.githubusercontent.com/assets/11301876/6471754/bdeab3e0-c1bb-11e4-885b-151be93eab15.jpg)
![original](https://cloud.githubusercontent.com/assets/11301876/6471755/bdf5bfd8-c1bb-11e4-9ede-e5be414ec4b7.jpg)

**Comment by hancho123** [comment]
Sorry if my editing is not great. It's my first time using Github.

**Comment by zachfeldman** [comment]
Hey @hancho123 that's ok! You should break up each of your problems into separate issues, not one big one. This way we can take a look at each of them in detail.

**Comment by hancho123** [comment]
Got it. Let me break this into 3 parts.
