### ISSUE TITLE
Demo video is down due to copyright request

### ISSUE THREAD

**Issue by s0uls** [zachfeldman/alexa-home#30]
Just to let you guys know.

Youtube has pullen the video 

"This video contains content from Believe Music, who has blocked it in your country on copyright grounds."

**Comment by zachfeldman** [comment]
Hey thanks! What country are you in?

**Comment by s0uls** [comment]
Argentina. Thanks for the quick reply

**Comment by zachfeldman** [comment]
No worries! Added another link to READMe to the video in my Dropbox @s0uls :)

**Comment by s0uls** [comment]
Great, this can be closed then =D

On Mon, Jul 27, 2015 at 4:07 PM, Zach Feldman notifications@github.com
wrote:

> No worries! Added another link to READMe to the video in my Dropbox @s0uls
> https://github.com/s0uls :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zachfeldman/alexa-home/issues/30#issuecomment-125308590
> .

## 

http://about.me/s0uls
