### ISSUE TITLE
Tag a release for the noobs to download archives.

### ISSUE THREAD

**Issue by funkytaco** [zachfeldman/alexa-home#31]

**Comment by zachfeldman** [comment]
Hey @funkytaco , sure although there aren't really any, "releases" or major version of this project. Couldn't you just download from the project homepage using the "download zip" button?

Either way, made a release and closing this issue :)

**Comment by funkytaco** [comment]
My bad. I forgot about that option. Was trying to help a reddit user who knows nothing about software dev.
