### ISSUE TITLE
Typo in "Getting Started"

### ISSUE THREAD

**Issue by hancho123** [zachfeldman/alexa-home#4]
4) Type chmod +x startScript.sh && ./startupScript.sh

Should be:

Type chmod +x startupScript.sh && ./startupScript.sh

**Comment by zachfeldman** [comment]
It is currently startScript.sh and should be startupScript.sh, right?

If so, please submit a pull request to fix this issue @hancho123 - doesn't require any coding knowledge to fix. 

https://help.github.com/articles/creating-a-pull-request/

**Comment by hancho123** [comment]
That's correct! I just placed the pull request..

**Comment by zachfeldman** [comment]
Don't close the issue until the Pull Request is closed - also see my comment in the pull request. I don't have time to explain what a Pull Request is but spend some time getting familiar and if you have questions, I can try to explain them.
