### ISSUE TITLE
Inserting jQuery into Chrome in Echo history comes up with problem

### ISSUE THREAD

**Issue by hancho123** [zachfeldman/alexa-home#5]
Hi!

When I put:
var lastCommand;
$(document).ajaxComplete(function(){
  command = $(".dd-title.d-dialog-title").first().text()
  if(lastCommand != command){
    $.get("http://localhost:4567/command?q="+command)
    lastCommand = command;
  }
})

I get the following:

GET http://localhost:4567/command?q=alexa%20stop&_=1425415875478 net::ERR_CONNECTION_REFUSED

or 

GET http://localhost:4567/command?q=alexa%20stop&_=1425416231226 net::ERR_CONNECTION_REFUSED

Not sure if this is a problem...

Thank you Zach!

**Comment by zachfeldman** [comment]
Hey @hancho123 , this is simply because the Sinatra server is not running. Once you get it running successfully, this problem should go away. Closing for now.

**Comment by hancho123** [comment]
Thank you!
