### ISSUE TITLE
Invalid JSON from client.rb

### ISSUE THREAD

**Issue by sarkonovich** [zachfeldman/alexa-home#8]
This error started showing up for me earlier today:

JSON::ParserError: A JSON text must at least contain two octets!
from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'

It seems like Hue added a redirect to:

https://client-eastwood-dot-hue-prod-us.appspot.com/api/nupnp

from

https://www.meethue.com/api/nupnp

I changed the address in client.rb and all is well again.

**Comment by sarkonovich** [comment]
This has been fixed in the Hue gem now.

**Comment by zachfeldman** [comment]
Good to hear! Thanks @sarkonovich for looking out.
