### ISSUE TITLE
Separating watir code into own gem.

### ISSUE THREAD

**Issue by KellyMahan** [zachfeldman/alexa-home#9]
I'm working on my own automation making use of the Wink hub and api.

https://github.com/KellyMahan/winker

Until a proper SDK is usable I'd like to make use of just your watir code with a configurable callback url.  Easiest way is just create a gem with an executable. 

I am trying to make it as modular as possible. I already have the basic Winker gem written. The readme explains it pretty well.

Winker-Rails is in progress but not releasable yet. It will be web interface for setting up logic that wink doesn't provide for.

Winker-Voice which I haven't started yet, will be the ai for parsing text strings for the proper commands.

All that i'm lacking is an easy way to get the commands from the echo device is something like your watir code. I may even add some additional functionality for playing music as part of the automation.

If it's not something you have time for then I can create it and attribute it to you.

**Comment by zachfeldman** [comment]
Hey @KellyMahan , do what you'd like, but please attribute me and the alexaho.me project. Thanks!

**Comment by KellyMahan** [comment]
Heres my first "working" version. Test it out take a look and let me know what you think.
https://github.com/KellyMahan/AmazonEchoJS

**Comment by zachfeldman** [comment]
Nice, two things though:

1) It's @zachfeldman, not @zachfeldmon
2) I don't think it's really fair to just credit me for the "original inspiration" of this project - I looked at your code and a lot of it is just copied and pasted from my watir-login file. Perhaps, "Majority of code written by @zachfeldman" might be more appropriate, or, "Portions of code written by @zachfeldman"?

**Comment by KellyMahan** [comment]
Sorry about the misspelling. Updated the readme as well.

**Comment by zachfeldman** [comment]
No worries - this looks good @KellyMahan . Just like to get credit for my work if possible =). Nice job!!
